### ISSUE TITLE
Be able to edit times before commit

### ISSUE THREAD

**Issue by rstefko** [rstefko/TimeClock#13]

**Comment by jirkaehm** [comment]
Lets continue with discussion here.

```
The problem here is that time sheets should not overlap, but we can start with some simple scenarios (eg. allow edit on last time sheet).
```

Yes, you are correct, but I think user should be able to simply fix the times to correct values, because sometimes we do just phone support etc..

We are trying to mainly solve the issue with users not reporting anything, we do not really care about minutes.
