### ISSUE TITLE
Error while installing

### ISSUE THREAD

**Issue by mtvrdy** [rstefko/TimeClock#5]
Hi there, 
We are getting this error while trying to instal TimeClock. This happened with 5 users. Also tried to run it from cmd as admin but nothing works

![TimeClock_error](https://user-images.githubusercontent.com/54977706/64410871-41d52f80-d08c-11e9-9c65-f913c8c1b603.PNG)

**Comment by rstefko** [comment]
Please check that API is running correctly on your server: [https://kb.eway-crm.com/faq-1/server/activate-eway-crm-api-wcfservice-on-the-server](https://kb.eway-crm.com/faq-1/server/activate-eway-crm-api-wcfservice-on-the-server)
