### ISSUE TITLE
Problem with commiting

### ISSUE THREAD

**Issue by sebekmartin** [rstefko/TimeClock#6]
Hello, 
we found an issue, that when someone forgets to stop TimeClock after leaving work, the timer is running until 0:00 next day. After that, the user can't commit this record, because of a bad time. You have to close TimeClock, then find history.xml file and delete this file. After that, the bad record is out and you can continue with committing. Is possible to solve that problem somehow? For example, that timer will always stop before midnight?
Thank you

**Comment by rstefko** [comment]
Hi @sebekmartin,

In the summary window when you commit your time sheets, there is an option to delete item by selecting it and pressing Del key.

Regards
Roman
